require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'workouttimerglobaltimer' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFBAdMob', :path => '../node_modules/@react-native-firebase/admob'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  target 'workouttimerglobaltimerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'workouttimerglobaltimer-tvOS' do
  # Pods for workouttimerglobaltimer-tvOS

  target 'workouttimerglobaltimer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
